import re
def normalize_job(title: str, keyword: str = "") -> str:
    t   = title.lower().strip()
    k   = keyword.lower().strip() if keyword else ""
    ref = k if k else t

    if re.search(r"unity|unreal engine|game programmer|game artist|game designer", ref): return "game developer"
    if re.search(r"flutter|react native|react native developer",                                           ref): return "mobile developer"
    if re.search(r"golang|go developer",                                        ref): return "golang developer"
    if re.search(r"nlp|natural language|ai eng",                                       ref): return "ai engineer"
    if re.search(r"computer vision|ai engineer",                                                ref): return "ai engineer"
    if re.search(r"prompt engineer",                                                ref): return "ai engineer"
    if re.search(r"blockchain|smart contract|solidity",                             ref): return "blockchain developer"
    if re.search(r"embedded|firmware",                                              ref): return "embedded engineer"
    if re.search(r"ar/vr|augmented|virtual reality",                               ref): return "ar/vr developer"
    if re.search(r"mlops|ml ops",                                                   ref): return "mlops engineer"
    if re.search(r"site reliability|sre",                                       ref): return "devops engineer"
    if re.search(r"aws solution|azure cloud|cloud security|platform engineer|virtualization", ref): return "cloud engineer"
    if re.search(r"soc analyst|ethical hacker|application security|iam engineer",  ref): return "security engineer"
    if re.search(r"penetration|pentest|cyber security|information security",       ref): return "security engineer"
    if re.search(r"big data|analytics engineer",                                    ref): return "data engineer"
    if re.search(r"etl|etl developer",                                          ref): return "data engineer"
    if re.search(r"data architect",                                                 ref): return "data engineer"
    if re.search(r"dba|database admin",                                         ref): return "database administrator"
    if re.search(r"erp|sap consultant|salesforce",                                  ref): return "erp consultant"
    if re.search(r"scrum master",                                                   ref): return "scrum master"
    if re.search(r"product owner",                                                  ref): return "product manager"
    if re.search(r"it audit|it asset",                                              ref): return "it consultant"
    if re.search(r"cto|cio|vp of eng|engineering manager|software dev manager|it director", ref): return "engineering manager"
    if re.search(r"solutions architect|pre-sales|technical account",               ref): return "solutions architect"
    if re.search(r"ux research|interaction designer|information architect",        ref): return "ui/ux designer"
    if re.search(r"technical writer",                                               ref): return "technical writer"
    if re.search(r"noc engineer|network admin|desktop support|it network",        ref): return "network engineer"
    if re.search(r"release engineer",                                               ref): return "devops engineer"
    if re.search(r"machine learning|ml engineer",     t): return "machine learning engineer"
    if re.search(r"data scien",                        t): return "data scientist"
    if re.search(r"data analy|bi anal|business intel", t): return "data analyst"
    if re.search(r"data engineer|data warehouse",      t): return "data engineer"
    if re.search(r"devops|dev ops",                    t): return "devops engineer"
    if re.search(r"cloud|cloud eng",                 t): return "cloud engineer"
    if re.search(r"full.?stack|fullstack",             t): return "fullstack developer"
    if re.search(r"back.end|backend",                  t): return "backend developer"
    if re.search(r"front.end|frontend",                t): return "frontend developer"
    if re.search(r"android|ios developer|mobile",      t): return "mobile developer"
    if re.search(r"flutter",                           t): return "mobile developer"
    if re.search(r"\.net developer|c# developer",      t): return "dotnet developer"
    if re.search(r"java developer",                    t): return "java developer"
    if re.search(r"php developer",                     t): return "php developer"
    if re.search(r"python developer",                  t): return "python developer"
    if re.search(r"nodejs|node\.js",                   t): return "nodejs developer"
    if re.search(r"golang|go dev",                   t): return "golang developer"
    if re.search(r"ruby on rails|ruby developer",                     t): return "ruby developer"
    if re.search(r"rust developer",                t): return "rust developer"
    if re.search(r"scala developer",                   t): return "scala developer"
    if re.search(r"c\+\+ developer",                   t): return "cpp developer"
    if re.search(r"web developer",                     t): return "fullstack developer"
    if re.search(r"qa|quality assur|tester|test eng|automation test", t): return "qa engineer"
    if re.search(r"security|cybersec",                 t): return "security engineer"
    if re.search(r"network",                           t): return "network engineer"
    if re.search(r"system admin|sysadmin|linux admin", t): return "system administrator"
    if re.search(r"it support|helpdesk|technical support|application support", t): return "it support"
    if re.search(r"product manager",                   t): return "product manager"
    if re.search(r"project manager",                   t): return "it project manager"
    if re.search(r"business anal|system anal",         t): return "business analyst"
    if re.search(r"ui.?ux|ux designer|ui designer",   t): return "ui/ux designer"
    if re.search(r"it consultant|it operations|it infra", t): return "it consultant"
    if re.search(r"programmer|developer|engineer|software", t): return "software developer"

    cleaned = re.sub(r"[^a-zA-Z\s]", "", t)
    return re.sub(r"\s+", " ", cleaned).strip() or "software developer"
